
import { roadmaps } from '../src/data/roadmaps.ts';
import * as fs from 'fs';
import * as path from 'path';

async function runHealthCheck() {
  console.log('🚀 Starting StackForge Content Health Check...');
  
  const totalLessons = roadmaps.reduce((acc, roadmap) => 
    acc + roadmap.modules.reduce((mAcc, module) => mAcc + module.lessons.length, 0), 0
  );

  let totalRequiredAssets = totalLessons * 7; // Lesson, Cheatsheet, Quick Quiz, Mastery Quiz, Interview, Project, Tutor Example
  let foundAssets = 0;
  const missingAssets: Record<string, string[]> = {};
  const missingTopics: string[] = [];
  const priorityFixes: string[] = [];

  roadmaps.forEach(roadmap => {
    roadmap.modules.forEach(module => {
      module.lessons.forEach(lesson => {
        const assetRequirements = [
          { name: 'Lesson', check: () => !!lesson.whatIsIt },
          { name: 'Cheatsheet', check: () => !!lesson.cheatsheetSlug },
          { name: 'Quick Quiz', check: () => !!lesson.quizId },
          { name: 'Mastery Quiz', check: () => !!lesson.masteryQuizId },
          { name: 'Interview Questions', check: () => !!lesson.interviewSlug },
          { name: 'Project', check: () => !!lesson.projectSlug },
          { name: 'Tutor Example', check: () => !!lesson.tutorExampleSlug },
        ];

        const missingForThisLesson: string[] = [];
        assetRequirements.forEach(req => {
          if (req.check()) {
            foundAssets++;
          } else {
            missingForThisLesson.push(req.name);
          }
        });

        if (missingForThisLesson.length > 0) {
          missingAssets[lesson.slug] = missingForThisLesson;
          if (missingForThisLesson.length === assetRequirements.length) {
            missingTopics.push(`${roadmap.title} -> ${module.title} -> ${lesson.title}`);
          }
        }
      });
    });
  });

  const coverage = (foundAssets / totalRequiredAssets) * 100;
  
  // Priority fixes: Topics with 0% coverage or core topics
  Object.entries(missingAssets).forEach(([slug, missing]) => {
    if (missing.length > 5) {
      priorityFixes.push(`Topic ${slug}: Missing ${missing.length} essential assets`);
    }
  });

  const reportMarkdown = `
# STACKFORGE CONTENT COMPLETENESS REPORT
Date: ${new Date().toLocaleDateString()}

## 📊 Coverage Metrics
- **Overall Coverage:** ${coverage.toFixed(2)}%
- **Total Lessons:** ${totalLessons}
- **Required Assets per Lesson:** 7
- **Total Required Assets:** ${totalRequiredAssets}
- **Found Assets:** ${foundAssets}

## ⚠️ Missing Topics (0% Coverage)
${missingTopics.length > 0 ? missingTopics.map(t => `- ${t}`).join('\n') : 'No topics with 0% coverage! 🎉'}

## 🛠 Priority Fixes
${priorityFixes.length > 0 ? priorityFixes.map(f => `- ${f}`).join('\n') : 'No immediate priority fixes.'}

## 📋 Detailed Missing Assets
${Object.entries(missingAssets).map(([slug, missing]) => `- **${slug}**: ${missing.join(', ')}`).join('\n')}

---
*Generated by StackForge Content Health Check Engine*
`;

  const reportsDir = path.join(process.cwd(), 'reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir);
  }
  
  fs.writeFileSync(path.join(reportsDir, 'CONTENT_COMPLETENESS.md'), reportMarkdown);
  console.log('✅ Health check complete. Report generated at reports/CONTENT_COMPLETENESS.md');
}

runHealthCheck().catch(console.error);
